### ISSUE TITLE
Creating account associated with MSA account doesn't work for me

### ISSUE THREAD

**Issue by emgieer** [MicrosoftDocs/azure-sphere-issues#124] opened 2019-07-28 15:06 UTC
I am able to log in to azure portal with my personal account. But when I open Azure Active Directory i get popup informing about error (without any further details about this error). And when I try to open "Users" section of Azure Active directory, I see following error message: "Unable to complete due to service connection error, please try again later." and no button to create new user.

After logging in to azure portal, in developer tools console I can see following errors:
```
{"odata.error":{"code":"Request_InvalidRequestUrl","message":{"lang":"en","value":"Request url was invalid. The request should be like \/tenantdomainname\/Entity or \/$metadata. Tenant domain name can be any of the verified, unverified domain names or context id."}}}
```
It looks like it is associated with 400 Bad request to following call: https://graph.windows.net/isDirectoryFeatureEnabled?api-version=1.6-internal request-id: 55083909-66e3-46ea-925a-b1487675dd43

When entering azure active directory i get:
* 403 response to https://main.iam.ad.ext.azure.com/api/FeatureConfigurations
* 400 response to https://main.iam.ad.ext.azure.com/api/Common/GetDiagnosticsServiceToken
* 403 response to https://main.iam.ad.ext.azure.com/api/MsGraph/v1.0/organization/?$select=onPremisesSyncEnabled,onPremisesLastSyncDateTime

When entering users pane i get following errors:
* 403 response to https://graph.windows.net/myorganization/isDirectoryFeatureEnabled?api-version=1.6-internal
* 403 response to https://main.iam.ad.ext.azure.com/api/Users?searchText=&top=25&orderByThumbnails=false&maxThumbnailCount=999&filterValue=All&state=All&adminUnit=&searchByObjectId=false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5cac582-108f-ed21-5ebd-02d35aaf6c3d
* Version Independent ID: 47d7bf64-ece8-a0c1-b2b7-3b6b447f9a03
* Content: [Account requirements for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/install/azure-directory-account#feedback)
* Content Source: [AzureSphere/articles/install/azure-directory-account.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/install/azure-directory-account.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment] 2019-07-29 03:06
@emgieer  Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment] 2019-08-01 11:06
@emgieer This would require further investigation to find out the root cause. Can you please file a support request @ https://aka.ms/azsupt? If you do not have access to a support plan, please reach out @ AZCommunity@microsoft.com with a link to this Doc/Issue as well as your subscription ID and we can help get the support ticket opened for this issue.

**Comment by AshokPeddakotla-MSFT** [comment] 2019-08-02 10:38
Please reach out the support as per the above email. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by AshokPeddakotla-MSFT** 2019-08-02 10:38 UTC
Labels: cxp, in-progress, product-issue, triaged

**Comment by agschipor** [comment] 2019-08-18 19:49
@emgieer @AshokPeddakotla-MSFT  Hi! I'm experiencing the same problem. Did you solved it? Thanks!

**Comment by AshokPeddakotla-MSFT** [comment] 2019-08-19 07:38
@agschipor Can you please create a new issue with the detailed error message and the documentation which you are following?

**Comment by agschipor** [comment] 2019-08-19 07:41
I can do it, but it is exactly the same issue & documentation - I'm receiving the same errors. It will be better to create a new issue?

**Comment by emgieer** [comment] 2019-08-19 19:40
@agschipor I didn't solved it. I created new azure account. After that I went back to my existing account and this time everything worked OK. I'm not sure if creating new account influenced anything. I suspect that simply waiting 30 minutes after receiving error was sufficient to fix that issue for me.

**Comment by dirzhov** [comment] 2020-03-04 11:06
I have the same issue. I see POST request https://graph.windows.net/isDirectoryFeatureEnabled?api-version=1.6-internal with body
{directoryFeature: "B2CFeature"}
And response with status 400 is

**Comment by asergaz** [comment] 2020-03-05 11:27
Hello @dirzhov the document that this issue refers to no longer exists or was substantially changed. Can I kindly ask you to open a new issue under the proper doc so we can follow-up with the right context?

Thanks!
