### ISSUE TITLE
Linux troubleshooting is Broken link on Japanese

### ISSUE THREAD

**Issue by atKeitaroTakahashi** [MicrosoftDocs/azure-sphere-issues#245] opened 2020-07-30 05:16 UTC
Broken link on JP
https://docs.microsoft.com/ja-jp/azure-sphere/install/troubleshoot-linux-install

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 859e405c-bdf9-0012-e6f8-706968193b40
* Version Independent ID: d5a03e55-b23b-2144-0045-492dca006b02
* Content: [Windows での Azure Sphere のインストールおよびセットアップのトラブルシューティング](https://docs.microsoft.com/ja-jp/azure-sphere/install/troubleshoot-installation#feedback)
* Content Source: [AzureSphere/articles/install/troubleshoot-installation.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.ja-JP/blob/live-sxs/AzureSphere/articles/install/troubleshoot-installation.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by AshokPeddakotla-MSFT** [comment] 2020-07-30 14:57
@atKeitaroTakahashi  Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment] 2020-07-30 16:56
@pennyo Could you please look into this and fix?

**Comment by pennyo** [comment] 2020-07-30 19:27
@atKeitaroTakahashi We released Azure Sphere 20.07 on 29-July, along with an updated SDK and documentation. All the troubleshooting information for installation and startup is now in the [Troubleshoot Installation](https://docs.microsoft.com/azure-sphere/install/troubleshoot-installation) topic. It includes general information along with tips for both Windows- and Linux-specific problems. 

You're seeing this error because the Japanese (/ja-jp) localization has not yet caught up with the newly published /en-us version, so the Linux-specific topic no longer exists. The localization effort is underway; if I can get an estimate of when it will be complete, I'll respond here.

**Comment by pennyo** [comment] 2020-07-31 15:17
@atKeitaroTakahashi We believe the issue is fixed now. If this is not the case, please let us know. Otherwise we'll close this issue.

**Comment by AshokPeddakotla-MSFT** [comment] 2020-08-11 11:36
@atKeitaroTakahashi  As mentioned, this issue has been fixed. please check and let us know. 
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by AshokPeddakotla-MSFT** 2020-08-11 11:36 UTC
Labels: Pri2, assigned-to-author, azure-sphere/prod, doc-bug, triaged
