### ISSUE TITLE
Sample Project Will not build

### ISSUE THREAD

**Issue by gconz** [MicrosoftDocs/azure-sphere-issues#45] opened 2018-10-15 20:34 UTC
'Object reference not set to an instance of an object.' when trying to build the blink sample solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d6e378-a8c1-6984-2a5c-30f2d2ae9971
* Version Independent ID: de2f147d-3f19-2f80-0427-b25c8061b51b
* Content: [Blink sample application Quickstart - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/quickstarts/qs-blink-application)
* Content Source: [AzureSphere/articles/quickstarts/qs-blink-application.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/quickstarts/qs-blink-application.md)
* Product: **azure-sphere**
* GitHub Login: @pennyo
* Microsoft Alias: **azurespheredocs**

**Comment by EHUbels** [comment] 2018-10-21 19:49
Had the same problem on one PC. Started to compare and finally found that the SDK did not install correct, look at the far end bottom of VS Tools & Features, Individual Components if the SDK and for the IoT the Connected Services are installed.

Erik

**Comment by max1weber** [comment] 2018-11-02 12:17
'Object reference not set to an instance of an object.' when trying to build the blink sample solution.

Same issue here.  And " VS Tools & Features, Individual Components if the SDK and for the IoT the Connected Services are installed." there are installed

Perhaps some other prereqs missing?

**Comment by rajeshagadi** [comment] 2018-11-07 22:18
Facing the same problem as above.

Steps taken: At Step 2 above, soon after the project is created or soon after repon the project from the last build failures to build successfully. with below error message:

---------------------------
Microsoft Visual Studio
---------------------------
An exception has been encountered. This may be caused by an extension.
You can get more information by examining the file 'C:\Users\<user>\AppData\Roaming\Microsoft\VisualStudio\15.0_77a0b1ee\ActivityLog.xml'.
---------------------------
OK   
---------------------------

Looking at the activity log.. Following are the errors:

Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.CppSvc.Internal.CodeAnalysis.ICodeAnalysisService" but found 0 after applying applicable constraints.at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()at Microsoft.VisualStudio.VC.ManagedInterop.<>c.<Initialize>b__52_15()at System.Lazy`1.CreateValue()at System.Lazy`1.LazyInitValue()at System.Lazy`1.get_Value()at Microsoft.VisualStudio.VC.CodeAnalysis.ResultTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by gconz** [comment] 2018-11-07 22:55
I've found the solution. It has to do with the extension.  I used this tool to clean up VS MEF extension cache:

https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

Then I reinstalled the azSphere extension.

**Comment by thomastitze** [comment] 2018-12-22 22:15
Had the same challenge with the error message "An exception has been encountered. This may be caused by an extension." I did not had installed the "Desktop Development with C++". I use a fresh installed version of VS Studio 2017 15.9.4 on a clean Windows 10 1809 machine. After installing the "Desktop Development with C++" Experience, same error comes up right after the project was loaded. I used @gconz hin to clear the MEF cache after installing the extension and then everything worked and I was able to debug the code on the device.

**Comment by leang97** [comment] 2019-02-03 06:09
> Had the same challenge with the error message "An exception has been encountered. This may be caused by an extension." I did not had installed the "Desktop Development with C++". I use a fresh installed version of VS Studio 2017 15.9.4 on a clean Windows 10 1809 machine. After installing the "Desktop Development with C++" Experience, same error comes up right after the project was loaded. I used @gconz hin to clear the MEF cache after installing the extension and then everything worked and I was able to debug the code on the device.

Had the same issue just now, cleared the MEF cache and same issue still there, 'Object reference not set to an instance of an object.' when trying to build project. Installed Visual Studio Community 2017, then installed "Desktop Development with C++", got that issue popped, cleared MEF cache still had that problem. Now trying to repair Visual Studio......

**Comment by matsujirushi** [comment] 2019-02-03 12:52
@leang97 
Please install "Visual C++ tools for CMake and Linux" and "Embedded and IoT Development".
See [that](https://social.msdn.microsoft.com/Forums/en-US/9899bbda-790f-416d-9049-c2f524ec9b05/azure-sphere-mt3620blink1-fails-on-startup?forum=azuresphere).

**Comment by sergaz-msft** [comment] 2019-03-20 16:06
Hi all,
Before closing this issue @gconz can you please confirm that your issue is now solved?

Thank you!

**Comment by max1weber** [comment] 2019-03-20 16:18
Yes,

It is ok

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by sergaz-msft** [comment] 2019-03-21 08:46
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by sergaz-msft** 2019-03-21 08:46 UTC
Labels: cxp, product-issue, triaged
