### ISSUE TITLE
Error: Failed to get attached devices. on Visual Studio Code with Azure Sphere UI Run Start Debugging

### ISSUE THREAD

**Issue by mcousine** [MicrosoftDocs/azure-sphere-issues#298] opened 2022-07-28 20:22 UTC
Error: Failed to get attached devices.  on Visual Studio Code with Azure Sphere UI Run Start Debugging

![2022-07-28_16-15-11](https://user-images.githubusercontent.com/4398519/181629967-b5f73efe-c581-4fcc-a985-f7ed771bce36.jpg)

**Comment by AshokPeddakotla-MSFT** [comment] 2022-07-29 05:23
@mcousine Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by AshokPeddakotla-MSFT** [comment] 2022-08-04 10:04
@mcousine Apologies for the long delay. Can you please share the documentation you are following for the steps?

I'm unable to reproduce this issue. Can you confirm your device OS and SDK versions? Make sure you have updated the OS to the [latest version](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new#new-and-changed-features-in-the-2207-os). 

To verify the installed OS version on an attached device, use the following command:

> azsphere device show-os-version

To check which version of the SDK is installed on your local computer, use the following command:

> azsphere show-version

Also I suggest you follow [Troubleshoot Azure Sphere problems](https://docs.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation) for common issues and resolutions.

**Comment by AshokPeddakotla-MSFT** [comment] 2022-08-05 10:02
@mcousine This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements. After reviewing the ask, it seems like generic query and not a doc feedback.

Hence, we request you to please reach out in forums like [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) We have our engineers and other community members who will be happy to assist. Forums have a better suited audience for such queries. Once your issue is posted in forum, please do share the forum thread link here for tracking. 

If you have a document which you are following and if you think it needs an update, please let us know about that here.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Thank you

**Closed by AshokPeddakotla-MSFT** 2022-08-05 10:02 UTC
Labels: cxp, triaged, product-issue, azure-sphere/prod
